### ISSUE TITLE
GraphQL error when no events have a specified venue

### ISSUE THREAD

**Issue by chancestrickland** [kwelch/react-codeworking-site#12]
Just spun up the site locally and got a GraphQL error:

```
102:11  error  Cannot query field "venue" on type "EventbriteEvent"
```

Looks like this is because the only event returned from the EB query has a null value for `venue`. I'm not a GraphQL expert so I'm not sure how this might be handled best, but I was able to at least solve the problem by setting defaults something like this in the `gatsby-source-eventbrite` plugin (which is probably a little ugly):

```js
const _ = require('lodash');

// ...stuff

const processEvent = (event) => {
    const venueName = _.get(event, 'venue.name');
    const venueAddress = _.get(event, 'venue.address');
    const _event = {
      ...event,
      venue: {
        name: venueName || '',
        address: venueAddress || {
          localized_address_display: _.get(venueAddress, 'localized_address_display') || ''
        },
        ...event.venue
      },
    };
    // use `_event` for everything below...
}

// ...stuff
```

**Comment by kwelch** [comment]
I don't know much about it either, this may be helpful. 
http://graphql.org/learn/queries/#directives

**Comment by chancestrickland** [comment]
Haven't had much success yet experimenting with directives, but I'm at least comforted in seeing lots of other similar issues with updates from Gatsby maintainers that a new API is in the works to deal with issues created by automatic schema inference. Then I found this from a few days ago: https://www.gatsbyjs.org/blog/2019-03-04-new-schema-customization/

**Comment by kwelch** [comment]
fixed with kwelch/gatsby-plugin-source-eventbrite@487045408b35d40b5f5b24b95fec18c7528e74cc and a91ebe5
